################################
###     Homepage Routing     ###
################################
import_homepage:
    path:     /import/homepage
    defaults: { _controller: blackLabelImportBundle:Homepage:index }

################################
###     Function Routing     ###
################################
import_form:
    path:     /import/form/{clientId}
    defaults: { _controller: blackLabelImportBundle:Import:import }
    requirements:
        clientId: \d+
