<?php

namespace whiteLabel\BackOfficeBundle\Repository;

/**
 * Anomalie_paiementAnnuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Anomalie_paiementAnnuleRepository extends \Doctrine\ORM\EntityRepository
{
}
