<?php

namespace whiteLabel\BackOfficeBundle\Repository;

/**
 * Anomalie_desistementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Anomalie_desistementRepository extends \Doctrine\ORM\EntityRepository
{
}
