<?php

namespace whiteLabel\BackOfficeBundle\Repository;

/**
 * Anomalie_PNDRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Anomalie_PNDRepository extends \Doctrine\ORM\EntityRepository
{
}
