<?php

namespace whiteLabel\BackOfficeBundle\Repository;

/**
 * Cheque_rapprochementBancaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Cheque_rapprochementBancaireRepository extends \Doctrine\ORM\EntityRepository
{
}
