<?php

namespace whiteLabel\BackOfficeBundle\Repository;

/**
 * Client_Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Client_Repository extends \Doctrine\ORM\EntityRepository
{
}
