<?php

namespace whiteLabel\BackOfficeBundle\Repository;

/**
 * Client_banqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Client_banqueRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $clientId
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function findByClient($clientId)
    {
        $query = $this
            ->createQueryBuilder('cl')
            ->select('cl')
            ->join('cl.client', 'client_')
            ->addSelect('client_')
        ;

        $query = $query
            ->where('client_.id = :clientId')
            ->setParameters(array(
                'clientId' => $clientId
            ))
        ;

        return $query;
    }
}
