<?php

namespace whiteLabel\BackOfficeBundle\Repository;

/**
 * Client_banqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Client_banqueRepository extends \Doctrine\ORM\EntityRepository
{
}
