<?php

namespace whiteLabel\BackOfficeBundle\Repository;

/**
 * Client_adresseNoteDebitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Client_adresseNoteDebitRepository extends \Doctrine\ORM\EntityRepository
{
}
