<?php

namespace whiteLabel\BackOfficeBundle\Repository;

/**
 * LettreChequeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LettreChequeRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * LettreChequeRepository constructor.
     * @param $em
     * @param \Doctrine\ORM\Mapping\ClassMetadata $class
     */
    public function __construct($em, \Doctrine\ORM\Mapping\ClassMetadata $class)
    {
        parent::__construct($em, $class);
    }



    /**
     * @param $clientId
     * @return array
     */
    public function findByClient($clientId)
    {
        $query = "
            SELECT  lc.id AS lettreChequeId,
                    lc.nom_modele AS lettreChequeNomModele,
                    lc.type_beneficiaire AS lettreChequeTypeBeneficiaire,
                    lc.file_url AS lettreChequeFileUrl,
                    lc.file_alt AS lettreChequeFileAlt,
                    lc.date_creation AS lettreChequeDateIntegration,
                    ci.nom AS clientNom
            FROM lettre_cheque lc
                INNER JOIN client_ c ON c.id = lc.client_id
                INNER JOIN client_information ci ON ci.id = c.client_information_id
            WHERE lc.client_id = " . $clientId . "
            ORDER BY lc.id DESC
        ";

        $stmt = $this->_em
            ->getConnection()
            ->prepare($query);
        $stmt->execute();

        return $stmt->fetchAll();
    }
}
