<?php

namespace whiteLabel\BackOfficeBundle\Repository;

/**
 * ModeleLettreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModeleLettreRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * ModeleLettreRepository constructor.
     * @param $em
     * @param \Doctrine\ORM\Mapping\ClassMetadata $class
     */
    public function __construct($em, \Doctrine\ORM\Mapping\ClassMetadata $class)
    {
        parent::__construct($em, $class);
    }



    /**
     * @param $clientId
     * @return array
     */
    public function findByClient($clientId)
    {
        $query = "
            SELECT  ml.id AS modeleLettreId,
                    ml.nom AS modeleLettreNom,
                    ml.type_beneficiaire AS modeleLettreTypeBeneficiaire,
                    ml.file_url AS modeleLettreFileUrl,
                    ml.file_alt AS modeleLettreFileAlt,
                    ml.date_creation AS modeleLettreDateIntegration,
                    ci.nom AS clientNom
            FROM modele_lettre ml
                INNER JOIN client_ c ON c.id = ml.client_id
                INNER JOIN client_information ci ON ci.id = c.client_information_id
            WHERE ml.client_id = " . $clientId . "
            ORDER BY ml.id DESC
        ";

        $stmt = $this->_em
            ->getConnection()
            ->prepare($query);
        $stmt->execute();

        return $stmt->fetchAll();
    }
}
