black_label_commentaire:
    resource: "@blackLabelCommentaireBundle/Resources/config/routing.yml"
    prefix:   /

black_label_historique:
    resource: "@blackLabelHistoriqueBundle/Resources/config/routing.yml"
    prefix:   /

###########################################
###     BlackLabel Bundles Routing      ###
###########################################
black_label_generic:
    resource: "@blackLabelGenericBundle/Resources/config/routing.yml"
    prefix:   /

###########################################
###     WhiteLabel Bundles Routing      ###
###########################################
white_label_web:
    resource: "@whiteLabelWebBundle/Resources/config/routing.yml"
    prefix:   /

white_label_main:
    resource: "@whiteLabelMainBundle/Resources/config/routing.yml"
    prefix:   /

white_label_back_office:
    resource: "@whiteLabelBackOfficeBundle/Resources/config/routing.yml"
    prefix:   /admin

white_label_front_office:
    resource: "@whiteLabelFrontOfficeBundle/Resources/config/routing.yml"
    prefix:   /member
