# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_USER:          ROLE_USER
        ROLE_MEMBER:        ROLE_MEMBER
        ROLE_COORDINATEUR:  ROLE_COORDINATEUR
        ROLE_GESTIONNAIRE:  ROLE_GESTIONNAIRE
        ROLE_ADMIN:         [ROLE_COORDINATEUR, ROLE_GESTIONNAIRE, ROLE_ALLOWED_TO_SWITCH]
        ROLE_SUPER_ADMIN:   [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # login area for backoffice users
        backoffice:
            context: primary_auth
            pattern: ^/admin

            form_login:
                csrf_token_generator: security.csrf.token_manager
                provider:     fos_userbundle
                login_path:   fos_admin_user_security_login
                check_path:   fos_admin_user_security_check
                default_target_path: /bo/dashboard
                success_handler: login_success_admin_handler

            logout:
                path:   fos_admin_user_security_logout
                target: '%logout_redirection_bo%'

            anonymous:    true
            remember_me:
                secret:   "%secret%"
                lifetime: 3600

        # defaut login area for frontoffice users
        frontoffice:
            context: primary_auth
            pattern: ^/

            form_login:
                csrf_token_generator: security.csrf.token_manager
                provider:   fos_userbundle
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                default_target_path: /fo/homepage
                success_handler: login_success_handler

            logout:
                path:   fos_user_security_logout
                target: '%logout_redirection_fo%'

            anonymous:    true
            remember_me:
                secret:   "%secret%"
                lifetime: 172800

    access_control:
        # back-office
        - { path: ^/admin/bo_login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: [ROLE_COORDINATEUR, ROLE_GESTIONNAIRE] }
        - { path: ^/member, roles: ROLE_MEMBER }
        # front-office
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/registration, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/profile, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/deconnexion$, role: IS_AUTHENTICATED_FULLY }
