<?php

namespace blackLabel\HistoriqueBundle\Repository;

/**
 * Historique_primeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Historique_primeRepository extends \Doctrine\ORM\EntityRepository
{
}
