<?php

namespace blackLabel\HistoriqueBundle\Repository;

/**
 * Historique_lotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Historique_lotRepository extends \Doctrine\ORM\EntityRepository
{
}
