<?php

namespace blackLabel\ImportBundle\Repository;

/**
 * Import_commandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Import_commandeRepository extends \Doctrine\ORM\EntityRepository
{
}
