<?php

namespace blackLabel\ImportBundle\Repository;

/**
 * Import_primeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Import_primeRepository extends \Doctrine\ORM\EntityRepository
{
}
