<?php

namespace blackLabel\ImportBundle\Repository;

/**
 * Import_canalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Import_canalRepository extends \Doctrine\ORM\EntityRepository
{
}
