################################
###     Homepage Routing     ###
################################
commentnaire_homepage:
    path:     /commentaire/homepage
    defaults: { _controller: blackLabelCommentaireBundle:Homepage:index }

################################
###     Function Routing     ###
################################

