################################
###       Upload Routing     ###
################################
upload_read:
    path:     /document/read/{uploadId}/{fileKey}/{extension}/{folderKey}
    defaults: { _controller: blackLabelGenericBundle:Upload:read }
    requirements:
        uploadId: \d+
        fileKey: \d+
        extension: jpeg|jpg|png|
        folderKey: \d+
