<?php

namespace blackLabel\GenericBundle\Repository;

/**
 * NutsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NutsRepository extends \Doctrine\ORM\EntityRepository
{
}
