<?php

namespace whiteLabel\MainBundle\Repository;

/**
 * ClusterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClusterRepository extends \Doctrine\ORM\EntityRepository
{
}
