<?php

namespace blackLabel\CommentaireBundle\Repository;

/**
 * Commentaire_primeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Commentaire_primeRepository extends \Doctrine\ORM\EntityRepository
{
}
