<?php

namespace blackLabel\CommentaireBundle\Repository;

/**
 * Commentaire_lotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Commentaire_lotRepository extends \Doctrine\ORM\EntityRepository
{
}
