###########################################
###     BlackLabel Bundles Routing      ###
###########################################
black_label_generic:
    resource: "@blackLabelGenericBundle/Resources/config/routing.yml"

black_label_import:
    resource: "@blackLabelImportBundle/Resources/config/routing.yml"

black_label_historique:
    resource: "@blackLabelHistoriqueBundle/Resources/config/routing.yml"

black_label_commentaire:
    resource: "@blackLabelCommentaireBundle/Resources/config/routing.yml"

###################################
###    FOSUser Custom Routing   ###
###################################
fos_admin_user_security_login:
    path:     /bo_login
    defaults: { _controller: whiteLabelBackOfficeBundle:Security:login }

fos_admin_user_security_check:
    path:     /bo_login_check
    defaults: { _controller: whiteLabelBackOfficeBundle:Security:check }
    requirements:
        _method: POST

fos_admin_user_security_logout:
    path:     /bo_logout
    defaults: { _controller: whiteLabelBackOfficeBundle:Security:logout }

################################
###     Dashboard Routing    ###
################################
bo_dashboard:
    path:     /bo/dashboard
    defaults: { _controller: whiteLabelBackOfficeBundle:Dashboard:index }

################################
###      Client Routing      ###
################################
client_list:
    path:     /client/list
    defaults: { _controller: whiteLabelBackOfficeBundle:Client:list }

client_create:
    path:     /client/create
    defaults: { _controller: whiteLabelBackOfficeBundle:Client:create }

client_read:
    path:     /client/read/{clientId}
    defaults: { _controller: whiteLabelBackOfficeBundle:Client:read }
    requirements:
        clientId: \d+

client_update:
    path:     /client/update/{clientId}
    defaults: { _controller: whiteLabelBackOfficeBundle:Client:update }
    requirements:
        clientId: \d+

client_delete:
    path:     /client/delete/{clientId}
    defaults: { _controller: whiteLabelBackOfficeBundle:Client:delete }
    requirements:
        clientId: \d+

################################
###     Homepage Routing     ###
################################
bo_homepage:
    path:     /bo/homepage/{clientId}
    defaults: { _controller: whiteLabelBackOfficeBundle:Homepage:index }
    requirements:
        clientId: \d+

################################
###       Lot Routing        ###
################################
lot_list:
    path:     /lot/list/{clientId}
    defaults: { _controller: whiteLabelBackOfficeBundle:Lot:list }
    requirements:
        clientId: \d+

lot_update:
    path:     /lot/update/{clientId}/{lotId}
    defaults: { _controller: whiteLabelBackOfficeBundle:Lot:update }
    requirements:
        clientId: \d+
        lotId: \d+

lot_export_noteDebit:
    path:     /lot/export/noteDebit/{clientId}/{lotId}
    defaults: { _controller: whiteLabelBackOfficeBundle:Lot:exportNoteDebit }
    requirements:
        clientId: \d+
        lotId: \d+

################################
###       Prime Routing      ###
################################
prime_list:
    path:     /prime/list/{clientId}
    defaults: { _controller: whiteLabelBackOfficeBundle:Prime:list }
    requirements:
        clientId: \d+

prime_read:
    path:     /prime/read/{clientId}/{primeId}
    defaults: { _controller: whiteLabelBackOfficeBundle:Prime:read }
    requirements:
        clientId: \d+
        primeId: \d+

prime_update:
    path:     /prime/update/{clientId}/{primeId}
    defaults: { _controller: whiteLabelBackOfficeBundle:Prime:update }
    requirements:
        clientId: \d+
        primeId: \d+

################################
###  Lettre Chèque Routing   ###
################################
lettreCheque_list:
    path:     /lettreCheque/list/{clientId}
    defaults: { _controller: whiteLabelBackOfficeBundle:LettreCheque:list }
    requirements:
        clientId: \d+

lettreCheque_create:
    path:     /lettreCheque/create/{clientId}
    defaults: { _controller: whiteLabelBackOfficeBundle:LettreCheque:create }
    requirements:
        clientId: \d+

lettreCheque_read:
    path:     /lettreCheque/read/{clientId}/{lettreChequeId}
    defaults: { _controller: whiteLabelBackOfficeBundle:LettreCheque:read }
    requirements:
        clientId: \d+
        lettreChequeId: \d+

lettreCheque_update:
    path:     /lettreCheque/update/{clientId}/{lettreChequeId}
    defaults: { _controller: whiteLabelBackOfficeBundle:LettreCheque:update }
    requirements:
        clientId: \d+
        lettreChequeId: \d+
