services:
    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    #  S E R V I C E
    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    white_label.service.lot:
        class: whiteLabel\BackOfficeBundle\Service\LotService
        arguments: ['@doctrine', '@service_container']

    white_label.service.prime:
        class: whiteLabel\BackOfficeBundle\Service\PrimeService
        arguments: ['@doctrine', '@service_container']

    white_label.service.modeleLettre:
        class: whiteLabel\BackOfficeBundle\Service\ModeleLettreService
        arguments: ['@doctrine', '@service_container']

    white_label.service.cheque:
        class: whiteLabel\BackOfficeBundle\Service\ChequeService
        arguments: ['@doctrine', '@service_container']

    white_label.service.anomalie:
        class: whiteLabel\BackOfficeBundle\Service\AnomalieService
        arguments: ['@doctrine', '@service_container']

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    #  F O R M S   E N T I T Y   M A N A G E R
    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    entityManager.formType.chequeStock:
        class: whiteLabel\BackOfficeBundle\Form\Cheque_stockType
        tags:
            - { name: form.type, alias: form_em }
        arguments: ['@doctrine']

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    #  S E C U R I T Y
    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    white_label.service.security:
        class: whiteLabel\BackOfficeBundle\Service\SecurityService
        arguments: ['@doctrine', '@service_container']
