###################################
###   FOSUser Custom Routing    ###
###################################
fos_user_profile_show:
    path:     /profile
    defaults: { _controller: FOSUserBundle:Profile:show }
    requirements:
        _method: GET

################################
###     Homepage Routing     ###
################################
fo_homepage:
    path:     /fo/homepage
    defaults: { _controller: whiteLabelFrontOfficeBundle:Homepage:index }
